import type Client from '../Client';
import ApplicationCommandPermissionsUpdate from './ApplicationCommandPermissionsUpdate';
import AutoModerationActionExecution from './AutoModerationActionExecution';
import AutoModerationRuleCreate from './AutoModerationRuleCreate';
import AutoModerationRuleDelete from './AutoModerationRuleDelete';
import AutoModerationRuleUpdate from './AutoModerationRuleUpdate';
import ChannelCreate from './ChannelCreate';
import ChannelDelete from './ChannelDelete';
import ChannelUpdate from './ChannelUpdate';
import GuildAuditLogEntryCreate from './GuildAuditLogEntryCreate';
import GuildBanAdd from './GuildBanAdd';
import GuildBanRemove from './GuildBanRemove';
import GuildChannelsPositionUpdate from './GuildChannelsPositionUpdate';
import GuildDelete from './GuildDelete';
import GuildEmojiCreate from './GuildEmojiCreate';
import GuildEmojiDelete from './GuildEmojiDelete';
import GuildEmojiUpdate from './GuildEmojiUpdate';
import GuildEmojisUpdate from './GuildEmojisUpdate';
import GuildIntegrationsUpdate from './GuildIntegrationsUpdate';
import GuildMemberRemove from './GuildMemberRemove';
import GuildMemberUpdate from './GuildMemberUpdate';
import GuildRoleCreate from './GuildRoleCreate';
import GuildRoleDelete from './GuildRoleDelete';
import GuildRoleUpdate from './GuildRoleUpdate';
import GuildRolesPositionUpdate from './GuildRolesPositionUpdate';
import GuildScheduledEventCreate from './GuildScheduledEventCreate';
import GuildScheduledEventDelete from './GuildScheduledEventDelete';
import GuildScheduledEventUpdate from './GuildScheduledEventUpdate';
import GuildScheduledEventUserAdd from './GuildScheduledEventUserAdd';
import GuildScheduledEventUserRemove from './GuildScheduledEventUserRemove';
import GuildStickerCreate from './GuildStickerCreate';
import GuildStickerDelete from './GuildStickerDelete';
import GuildStickerUpdate from './GuildStickerUpdate';
import GuildStickersUpdate from './GuildStickersUpdate';
import GuildUpdate from './GuildUpdate';
import InviteCreate from './InviteCreate';
import InviteDelete from './InviteDelete';
import MessageCreate from './MessageCreate';
import MessageDelete from './MessageDelete';
import MessageDeleteBulk from './MessageDeleteBulk';
import MessagePollVoteAdd from './MessagePollVoteAdd';
import MessagePollVoteRemove from './MessagePollVoteRemove';
import MessageReactionAdd from './MessageReactionAdd';
import MessageReactionRemove from './MessageReactionRemove';
import MessageReactionRemoveAll from './MessageReactionRemoveAll';
import MessageReactionRemoveEmoji from './MessageReactionRemoveEmoji';
import MessageUpdate from './MessageUpdate';
import PresenceUpdate from './PresenceUpdate';
import StageInstanceCreate from './StageInstanceCreate';
import StageInstanceDelete from './StageInstanceDelete';
import StageInstanceUpdate from './StageInstanceUpdate';
import ThreadCreate from './ThreadCreate';
import ThreadDelete from './ThreadDelete';
import ThreadListSync from './ThreadListSync';
import ThreadMemberUpdate from './ThreadMemberUpdate';
import ThreadMembersUpdate from './ThreadMembersUpdate';
import TypingStart from './TypingStart';
import UserUpdate from './UserUpdate';
import VoiceStateUpdate from './VoiceStateUpdate';
import WebhooksUpdate from './WebhooksUpdate';
declare class ActionsManager {
    client: Client;
    injectedUser: symbol;
    injectedChannel: symbol;
    injectedMessage: symbol;
    ApplicationCommandPermissionsUpdate: ApplicationCommandPermissionsUpdate;
    AutoModerationActionExecution: AutoModerationActionExecution;
    AutoModerationRuleCreate: AutoModerationRuleCreate;
    AutoModerationRuleDelete: AutoModerationRuleDelete;
    AutoModerationRuleUpdate: AutoModerationRuleUpdate;
    ChannelCreate: ChannelCreate;
    ChannelDelete: ChannelDelete;
    ChannelUpdate: ChannelUpdate;
    GuildAuditLogEntryCreate: GuildAuditLogEntryCreate;
    GuildBanAdd: GuildBanAdd;
    GuildBanRemove: GuildBanRemove;
    GuildChannelsPositionUpdate: GuildChannelsPositionUpdate;
    GuildDelete: GuildDelete;
    GuildEmojiCreate: GuildEmojiCreate;
    GuildEmojiDelete: GuildEmojiDelete;
    GuildEmojiUpdate: GuildEmojiUpdate;
    GuildEmojisUpdate: GuildEmojisUpdate;
    GuildIntegrationsUpdate: GuildIntegrationsUpdate;
    GuildMemberRemove: GuildMemberRemove;
    GuildMemberUpdate: GuildMemberUpdate;
    GuildRoleCreate: GuildRoleCreate;
    GuildRoleDelete: GuildRoleDelete;
    GuildRoleUpdate: GuildRoleUpdate;
    GuildRolesPositionUpdate: GuildRolesPositionUpdate;
    GuildScheduledEventCreate: GuildScheduledEventCreate;
    GuildScheduledEventDelete: GuildScheduledEventDelete;
    GuildScheduledEventUpdate: GuildScheduledEventUpdate;
    GuildScheduledEventUserAdd: GuildScheduledEventUserAdd;
    GuildScheduledEventUserRemove: GuildScheduledEventUserRemove;
    GuildStickerCreate: GuildStickerCreate;
    GuildStickerDelete: GuildStickerDelete;
    GuildStickerUpdate: GuildStickerUpdate;
    GuildStickersUpdate: GuildStickersUpdate;
    GuildUpdate: GuildUpdate;
    InviteCreate: InviteCreate;
    InviteDelete: InviteDelete;
    MessageCreate: MessageCreate;
    MessageDelete: MessageDelete;
    MessageDeleteBulk: MessageDeleteBulk;
    MessagePollVoteAdd: MessagePollVoteAdd;
    MessagePollVoteRemove: MessagePollVoteRemove;
    MessageReactionAdd: MessageReactionAdd;
    MessageReactionRemove: MessageReactionRemove;
    MessageReactionRemoveAll: MessageReactionRemoveAll;
    MessageReactionRemoveEmoji: MessageReactionRemoveEmoji;
    MessageUpdate: MessageUpdate;
    PresenceUpdate: PresenceUpdate;
    StageInstanceCreate: StageInstanceCreate;
    StageInstanceDelete: StageInstanceDelete;
    StageInstanceUpdate: StageInstanceUpdate;
    ThreadCreate: ThreadCreate;
    ThreadDelete: ThreadDelete;
    ThreadListSync: ThreadListSync;
    ThreadMemberUpdate: ThreadMemberUpdate;
    ThreadMembersUpdate: ThreadMembersUpdate;
    TypingStart: TypingStart;
    UserUpdate: UserUpdate;
    VoiceStateUpdate: VoiceStateUpdate;
    WebhooksUpdate: WebhooksUpdate;
    constructor(client: Client);
}
export default ActionsManager;
