import type Client from '../Client';
import ApplicationCommandPermissionsUpdate from './ApplicationCommandPermissionsUpdate';
import AutoModerationActionExecution from './AutoModerationActionExecution';
import AutoModerationRuleCreate from './AutoModerationRuleCreate';
import AutoModerationRuleDelete from './AutoModerationRuleDelete';
import AutoModerationRuleUpdate from './AutoModerationRuleUpdate';
import ChannelCreate from './ChannelCreate';
import ChannelDelete from './ChannelDelete';
import ChannelUpdate from './ChannelUpdate';
import GuildAuditLogEntryCreate from './GuildAuditLogEntryCreate';
import GuildBanAdd from './GuildBanAdd';
import GuildBanRemove from './GuildBanRemove';
import GuildChannelsPositionUpdate from './GuildChannelsPositionUpdate';
import GuildDelete from './GuildDelete';
import GuildEmojiCreate from './GuildEmojiCreate';
import GuildEmojiDelete from './GuildEmojiDelete';
import GuildEmojiUpdate from './GuildEmojiUpdate';
import GuildEmojisUpdate from './GuildEmojisUpdate';
import GuildIntegrationsUpdate from './GuildIntegrationsUpdate';
import GuildMemberRemove from './GuildMemberRemove';
import GuildMemberUpdate from './GuildMemberUpdate';
import GuildRoleCreate from './GuildRoleCreate';
import GuildRoleDelete from './GuildRoleDelete';
import GuildRoleUpdate from './GuildRoleUpdate';
import GuildRolesPositionUpdate from './GuildRolesPositionUpdate';
import GuildScheduledEventCreate from './GuildScheduledEventCreate';
import GuildScheduledEventDelete from './GuildScheduledEventDelete';
import GuildScheduledEventUpdate from './GuildScheduledEventUpdate';
import GuildScheduledEventUserAdd from './GuildScheduledEventUserAdd';
import GuildScheduledEventUserRemove from './GuildScheduledEventUserRemove';
import GuildStickerCreate from './GuildStickerCreate';
import GuildStickerDelete from './GuildStickerDelete';
import GuildStickerUpdate from './GuildStickerUpdate';
import GuildStickersUpdate from './GuildStickersUpdate';
import GuildUpdate from './GuildUpdate';
import InviteCreate from './InviteCreate';
import InviteDelete from './InviteDelete';
import MessageCreate from './MessageCreate';
import MessageDelete from './MessageDelete';
import MessageDeleteBulk from './MessageDeleteBulk';
import MessagePollVoteAdd from './MessagePollVoteAdd';
import MessagePollVoteRemove from './MessagePollVoteRemove';
import MessageReactionAdd from './MessageReactionAdd';
import MessageReactionRemove from './MessageReactionRemove';
import MessageReactionRemoveAll from './MessageReactionRemoveAll';
import MessageReactionRemoveEmoji from './MessageReactionRemoveEmoji';
import MessageUpdate from './MessageUpdate';
import PresenceUpdate from './PresenceUpdate';
import StageInstanceCreate from './StageInstanceCreate';
import StageInstanceDelete from './StageInstanceDelete';
import StageInstanceUpdate from './StageInstanceUpdate';
import ThreadCreate from './ThreadCreate';
import ThreadDelete from './ThreadDelete';
import ThreadListSync from './ThreadListSync';
import ThreadMemberUpdate from './ThreadMemberUpdate';
import ThreadMembersUpdate from './ThreadMembersUpdate';
import TypingStart from './TypingStart';
import UserUpdate from './UserUpdate';
import VoiceStateUpdate from './VoiceStateUpdate';
import WebhooksUpdate from './WebhooksUpdate';
import type Action from './Action';

class ActionsManager {
  client: Client;
  injectedUser: symbol;
  injectedChannel: symbol;
  injectedMessage: symbol;
  
  ApplicationCommandPermissionsUpdate: ApplicationCommandPermissionsUpdate;
  AutoModerationActionExecution: AutoModerationActionExecution;
  AutoModerationRuleCreate: AutoModerationRuleCreate;
  AutoModerationRuleDelete: AutoModerationRuleDelete;
  AutoModerationRuleUpdate: AutoModerationRuleUpdate;
  ChannelCreate: ChannelCreate;
  ChannelDelete: ChannelDelete;
  ChannelUpdate: ChannelUpdate;
  GuildAuditLogEntryCreate: GuildAuditLogEntryCreate;
  GuildBanAdd: GuildBanAdd;
  GuildBanRemove: GuildBanRemove;
  GuildChannelsPositionUpdate: GuildChannelsPositionUpdate;
  GuildDelete: GuildDelete;
  GuildEmojiCreate: GuildEmojiCreate;
  GuildEmojiDelete: GuildEmojiDelete;
  GuildEmojiUpdate: GuildEmojiUpdate;
  GuildEmojisUpdate: GuildEmojisUpdate;
  GuildIntegrationsUpdate: GuildIntegrationsUpdate;
  GuildMemberRemove: GuildMemberRemove;
  GuildMemberUpdate: GuildMemberUpdate;
  GuildRoleCreate: GuildRoleCreate;
  GuildRoleDelete: GuildRoleDelete;
  GuildRoleUpdate: GuildRoleUpdate;
  GuildRolesPositionUpdate: GuildRolesPositionUpdate;
  GuildScheduledEventCreate: GuildScheduledEventCreate;
  GuildScheduledEventDelete: GuildScheduledEventDelete;
  GuildScheduledEventUpdate: GuildScheduledEventUpdate;
  GuildScheduledEventUserAdd: GuildScheduledEventUserAdd;
  GuildScheduledEventUserRemove: GuildScheduledEventUserRemove;
  GuildStickerCreate: GuildStickerCreate;
  GuildStickerDelete: GuildStickerDelete;
  GuildStickerUpdate: GuildStickerUpdate;
  GuildStickersUpdate: GuildStickersUpdate;
  GuildUpdate: GuildUpdate;
  InviteCreate: InviteCreate;
  InviteDelete: InviteDelete;
  MessageCreate: MessageCreate;
  MessageDelete: MessageDelete;
  MessageDeleteBulk: MessageDeleteBulk;
  MessagePollVoteAdd: MessagePollVoteAdd;
  MessagePollVoteRemove: MessagePollVoteRemove;
  MessageReactionAdd: MessageReactionAdd;
  MessageReactionRemove: MessageReactionRemove;
  MessageReactionRemoveAll: MessageReactionRemoveAll;
  MessageReactionRemoveEmoji: MessageReactionRemoveEmoji;
  MessageUpdate: MessageUpdate;
  PresenceUpdate: PresenceUpdate;
  StageInstanceCreate: StageInstanceCreate;
  StageInstanceDelete: StageInstanceDelete;
  StageInstanceUpdate: StageInstanceUpdate;
  ThreadCreate: ThreadCreate;
  ThreadDelete: ThreadDelete;
  ThreadListSync: ThreadListSync;
  ThreadMemberUpdate: ThreadMemberUpdate;
  ThreadMembersUpdate: ThreadMembersUpdate;
  TypingStart: TypingStart;
  UserUpdate: UserUpdate;
  VoiceStateUpdate: VoiceStateUpdate;
  WebhooksUpdate: WebhooksUpdate;

  constructor(client: Client) {
    this.client = client;

    // These symbols represent fully built data that we inject at times when calling actions manually.
    // Action#getUser for example, will return the injected data (which is assumed to be a built structure)
    // instead of trying to make it from provided data
    this.injectedUser = Symbol('djs.actions.injectedUser');
    this.injectedChannel = Symbol('djs.actions.injectedChannel');
    this.injectedMessage = Symbol('djs.actions.injectedMessage');

    this.ApplicationCommandPermissionsUpdate = new ApplicationCommandPermissionsUpdate(client);
    this.AutoModerationActionExecution = new AutoModerationActionExecution(client);
    this.AutoModerationRuleCreate = new AutoModerationRuleCreate(client);
    this.AutoModerationRuleDelete = new AutoModerationRuleDelete(client);
    this.AutoModerationRuleUpdate = new AutoModerationRuleUpdate(client);
    this.ChannelCreate = new ChannelCreate(client);
    this.ChannelDelete = new ChannelDelete(client);
    this.ChannelUpdate = new ChannelUpdate(client);
    this.GuildAuditLogEntryCreate = new GuildAuditLogEntryCreate(client);
    this.GuildBanAdd = new GuildBanAdd(client);
    this.GuildBanRemove = new GuildBanRemove(client);
    this.GuildChannelsPositionUpdate = new GuildChannelsPositionUpdate(client);
    this.GuildDelete = new GuildDelete(client);
    this.GuildEmojiCreate = new GuildEmojiCreate(client);
    this.GuildEmojiDelete = new GuildEmojiDelete(client);
    this.GuildEmojiUpdate = new GuildEmojiUpdate(client);
    this.GuildEmojisUpdate = new GuildEmojisUpdate(client);
    this.GuildIntegrationsUpdate = new GuildIntegrationsUpdate(client);
    this.GuildMemberRemove = new GuildMemberRemove(client);
    this.GuildMemberUpdate = new GuildMemberUpdate(client);
    this.GuildRoleCreate = new GuildRoleCreate(client);
    this.GuildRoleDelete = new GuildRoleDelete(client);
    this.GuildRoleUpdate = new GuildRoleUpdate(client);
    this.GuildRolesPositionUpdate = new GuildRolesPositionUpdate(client);
    this.GuildScheduledEventCreate = new GuildScheduledEventCreate(client);
    this.GuildScheduledEventDelete = new GuildScheduledEventDelete(client);
    this.GuildScheduledEventUpdate = new GuildScheduledEventUpdate(client);
    this.GuildScheduledEventUserAdd = new GuildScheduledEventUserAdd(client);
    this.GuildScheduledEventUserRemove = new GuildScheduledEventUserRemove(client);
    this.GuildStickerCreate = new GuildStickerCreate(client);
    this.GuildStickerDelete = new GuildStickerDelete(client);
    this.GuildStickerUpdate = new GuildStickerUpdate(client);
    this.GuildStickersUpdate = new GuildStickersUpdate(client);
    this.GuildUpdate = new GuildUpdate(client);
    this.InviteCreate = new InviteCreate(client);
    this.InviteDelete = new InviteDelete(client);
    this.MessageCreate = new MessageCreate(client);
    this.MessageDelete = new MessageDelete(client);
    this.MessageDeleteBulk = new MessageDeleteBulk(client);
    this.MessagePollVoteAdd = new MessagePollVoteAdd(client);
    this.MessagePollVoteRemove = new MessagePollVoteRemove(client);
    this.MessageReactionAdd = new MessageReactionAdd(client);
    this.MessageReactionRemove = new MessageReactionRemove(client);
    this.MessageReactionRemoveAll = new MessageReactionRemoveAll(client);
    this.MessageReactionRemoveEmoji = new MessageReactionRemoveEmoji(client);
    this.MessageUpdate = new MessageUpdate(client);
    this.PresenceUpdate = new PresenceUpdate(client);
    this.StageInstanceCreate = new StageInstanceCreate(client);
    this.StageInstanceDelete = new StageInstanceDelete(client);
    this.StageInstanceUpdate = new StageInstanceUpdate(client);
    this.ThreadCreate = new ThreadCreate(client);
    this.ThreadDelete = new ThreadDelete(client);
    this.ThreadListSync = new ThreadListSync(client);
    this.ThreadMemberUpdate = new ThreadMemberUpdate(client);
    this.ThreadMembersUpdate = new ThreadMembersUpdate(client);
    this.TypingStart = new TypingStart(client);
    this.UserUpdate = new UserUpdate(client);
    this.VoiceStateUpdate = new VoiceStateUpdate(client);
    this.WebhooksUpdate = new WebhooksUpdate(client);
  }
}

export default ActionsManager;
