import type { GatewayHandler } from './types';
import READY from './READY';
import RESUMED from './RESUMED';
import APPLICATION_COMMAND_CREATE from './APPLICATION_COMMAND_CREATE';
import APPLICATION_COMMAND_DELETE from './APPLICATION_COMMAND_DELETE';
import APPLICATION_COMMAND_UPDATE from './APPLICATION_COMMAND_UPDATE';
import APPLICATION_COMMAND_PERMISSIONS_UPDATE from './APPLICATION_COMMAND_PERMISSIONS_UPDATE';
import AUTO_MODERATION_ACTION_EXECUTION from './AUTO_MODERATION_ACTION_EXECUTION';
import AUTO_MODERATION_RULE_CREATE from './AUTO_MODERATION_RULE_CREATE';
import AUTO_MODERATION_RULE_DELETE from './AUTO_MODERATION_RULE_DELETE';
import AUTO_MODERATION_RULE_UPDATE from './AUTO_MODERATION_RULE_UPDATE';
import GUILD_CREATE from './GUILD_CREATE';
import GUILD_DELETE from './GUILD_DELETE';
import GUILD_UPDATE from './GUILD_UPDATE';
import INVITE_CREATE from './INVITE_CREATE';
import INVITE_DELETE from './INVITE_DELETE';
import GUILD_MEMBER_ADD from './GUILD_MEMBER_ADD';
import GUILD_MEMBER_REMOVE from './GUILD_MEMBER_REMOVE';
import GUILD_MEMBER_UPDATE from './GUILD_MEMBER_UPDATE';
import GUILD_MEMBERS_CHUNK from './GUILD_MEMBERS_CHUNK';
import GUILD_INTEGRATIONS_UPDATE from './GUILD_INTEGRATIONS_UPDATE';
import GUILD_ROLE_CREATE from './GUILD_ROLE_CREATE';
import GUILD_ROLE_DELETE from './GUILD_ROLE_DELETE';
import GUILD_ROLE_UPDATE from './GUILD_ROLE_UPDATE';
import GUILD_BAN_ADD from './GUILD_BAN_ADD';
import GUILD_BAN_REMOVE from './GUILD_BAN_REMOVE';
import GUILD_EMOJIS_UPDATE from './GUILD_EMOJIS_UPDATE';
import CHANNEL_CREATE from './CHANNEL_CREATE';
import CHANNEL_DELETE from './CHANNEL_DELETE';
import CHANNEL_UPDATE from './CHANNEL_UPDATE';
import CHANNEL_PINS_UPDATE from './CHANNEL_PINS_UPDATE';
import MESSAGE_CREATE from './MESSAGE_CREATE';
import MESSAGE_DELETE from './MESSAGE_DELETE';
import MESSAGE_UPDATE from './MESSAGE_UPDATE';
import MESSAGE_DELETE_BULK from './MESSAGE_DELETE_BULK';
import MESSAGE_REACTION_ADD from './MESSAGE_REACTION_ADD';
import MESSAGE_REACTION_REMOVE from './MESSAGE_REACTION_REMOVE';
import MESSAGE_REACTION_REMOVE_ALL from './MESSAGE_REACTION_REMOVE_ALL';
import MESSAGE_REACTION_REMOVE_EMOJI from './MESSAGE_REACTION_REMOVE_EMOJI';
import THREAD_CREATE from './THREAD_CREATE';
import THREAD_UPDATE from './THREAD_UPDATE';
import THREAD_DELETE from './THREAD_DELETE';
import THREAD_LIST_SYNC from './THREAD_LIST_SYNC';
import THREAD_MEMBER_UPDATE from './THREAD_MEMBER_UPDATE';
import THREAD_MEMBERS_UPDATE from './THREAD_MEMBERS_UPDATE';
import USER_UPDATE from './USER_UPDATE';
import PRESENCE_UPDATE from './PRESENCE_UPDATE';
import TYPING_START from './TYPING_START';
import VOICE_CHANNEL_EFFECT_SEND from './VOICE_CHANNEL_EFFECT_SEND';
import VOICE_STATE_UPDATE from './VOICE_STATE_UPDATE';
import VOICE_SERVER_UPDATE from './VOICE_SERVER_UPDATE';
import WEBHOOKS_UPDATE from './WEBHOOKS_UPDATE';
import STAGE_INSTANCE_CREATE from './STAGE_INSTANCE_CREATE';
import STAGE_INSTANCE_UPDATE from './STAGE_INSTANCE_UPDATE';
import STAGE_INSTANCE_DELETE from './STAGE_INSTANCE_DELETE';
import GUILD_STICKERS_UPDATE from './GUILD_STICKERS_UPDATE';
import GUILD_SCHEDULED_EVENT_CREATE from './GUILD_SCHEDULED_EVENT_CREATE';
import GUILD_SCHEDULED_EVENT_UPDATE from './GUILD_SCHEDULED_EVENT_UPDATE';
import GUILD_SCHEDULED_EVENT_DELETE from './GUILD_SCHEDULED_EVENT_DELETE';
import GUILD_SCHEDULED_EVENT_USER_ADD from './GUILD_SCHEDULED_EVENT_USER_ADD';
import GUILD_SCHEDULED_EVENT_USER_REMOVE from './GUILD_SCHEDULED_EVENT_USER_REMOVE';
import GUILD_AUDIT_LOG_ENTRY_CREATE from './GUILD_AUDIT_LOG_ENTRY_CREATE';
import RELATIONSHIP_ADD from './RELATIONSHIP_ADD';
import RELATIONSHIP_REMOVE from './RELATIONSHIP_REMOVE';
import RELATIONSHIP_UPDATE from './RELATIONSHIP_UPDATE';
import USER_NOTE_UPDATE from './USER_NOTE_UPDATE';
import CHANNEL_RECIPIENT_ADD from './CHANNEL_RECIPIENT_ADD';
import CHANNEL_RECIPIENT_REMOVE from './CHANNEL_RECIPIENT_REMOVE';
import INTERACTION_MODAL_CREATE from './INTERACTION_MODAL_CREATE';
import USER_REQUIRED_ACTION_UPDATE from './USER_REQUIRED_ACTION_UPDATE';
import CALL_CREATE from './CALL_CREATE';
import CALL_UPDATE from './CALL_UPDATE';
import CALL_DELETE from './CALL_DELETE';
import USER_SETTINGS_UPDATE from './USER_SETTINGS_UPDATE';
import USER_GUILD_SETTINGS_UPDATE from './USER_GUILD_SETTINGS_UPDATE';
import VOICE_CHANNEL_STATUS_UPDATE from './VOICE_CHANNEL_STATUS_UPDATE';
import MESSAGE_POLL_VOTE_ADD from './MESSAGE_POLL_VOTE_ADD';
import MESSAGE_POLL_VOTE_REMOVE from './MESSAGE_POLL_VOTE_REMOVE';

const handlers: Record<string, GatewayHandler> = {
  READY,
  RESUMED,
  APPLICATION_COMMAND_CREATE,
  APPLICATION_COMMAND_DELETE,
  APPLICATION_COMMAND_UPDATE,
  APPLICATION_COMMAND_PERMISSIONS_UPDATE,
  AUTO_MODERATION_ACTION_EXECUTION,
  AUTO_MODERATION_RULE_CREATE,
  AUTO_MODERATION_RULE_DELETE,
  AUTO_MODERATION_RULE_UPDATE,
  GUILD_CREATE,
  GUILD_DELETE,
  GUILD_UPDATE,
  INVITE_CREATE,
  INVITE_DELETE,
  GUILD_MEMBER_ADD,
  GUILD_MEMBER_REMOVE,
  GUILD_MEMBER_UPDATE,
  GUILD_MEMBERS_CHUNK,
  GUILD_INTEGRATIONS_UPDATE,
  GUILD_ROLE_CREATE,
  GUILD_ROLE_DELETE,
  GUILD_ROLE_UPDATE,
  GUILD_BAN_ADD,
  GUILD_BAN_REMOVE,
  GUILD_EMOJIS_UPDATE,
  CHANNEL_CREATE,
  CHANNEL_DELETE,
  CHANNEL_UPDATE,
  CHANNEL_PINS_UPDATE,
  MESSAGE_CREATE,
  MESSAGE_DELETE,
  MESSAGE_UPDATE,
  MESSAGE_DELETE_BULK,
  MESSAGE_REACTION_ADD,
  MESSAGE_REACTION_REMOVE,
  MESSAGE_REACTION_REMOVE_ALL,
  MESSAGE_REACTION_REMOVE_EMOJI,
  THREAD_CREATE,
  THREAD_UPDATE,
  THREAD_DELETE,
  THREAD_LIST_SYNC,
  THREAD_MEMBER_UPDATE,
  THREAD_MEMBERS_UPDATE,
  USER_UPDATE,
  PRESENCE_UPDATE,
  TYPING_START,
  VOICE_CHANNEL_EFFECT_SEND,
  VOICE_STATE_UPDATE,
  VOICE_SERVER_UPDATE,
  WEBHOOKS_UPDATE,
  STAGE_INSTANCE_CREATE,
  STAGE_INSTANCE_UPDATE,
  STAGE_INSTANCE_DELETE,
  GUILD_STICKERS_UPDATE,
  GUILD_SCHEDULED_EVENT_CREATE,
  GUILD_SCHEDULED_EVENT_UPDATE,
  GUILD_SCHEDULED_EVENT_DELETE,
  GUILD_SCHEDULED_EVENT_USER_ADD,
  GUILD_SCHEDULED_EVENT_USER_REMOVE,
  GUILD_AUDIT_LOG_ENTRY_CREATE,
  RELATIONSHIP_ADD,
  RELATIONSHIP_REMOVE,
  RELATIONSHIP_UPDATE,
  USER_NOTE_UPDATE,
  CHANNEL_RECIPIENT_ADD,
  CHANNEL_RECIPIENT_REMOVE,
  INTERACTION_MODAL_CREATE,
  USER_REQUIRED_ACTION_UPDATE,
  CALL_CREATE,
  CALL_UPDATE,
  CALL_DELETE,
  USER_SETTINGS_UPDATE,
  USER_GUILD_SETTINGS_UPDATE,
  VOICE_CHANNEL_STATUS_UPDATE,
  MESSAGE_POLL_VOTE_ADD,
  MESSAGE_POLL_VOTE_REMOVE,
};

export default handlers;
